n = int(input(' digite um numero para ver sua tabuada :'))
print('-'*12)
print('{} x{:2} = {:2}'.format(n, 1, n*1))
print('{} x{:2} = {:2}'.format(n, 1, n*2))
print('{} x{:2} = {:2}'.format(n, 1, n*3))
print('{} x{:2} = {:2}'.format(n, 1, n*4))
print('{} x{:2} = {:2}'.format(n, 1, n*5))
print('{} x{:2} = {:2}'.format(n, 1, n*6))
print('{} x{:2} = {:2}'.format(n, 1, n*7))
print('{} x{:2} = {:2}'.format(n, 1, n*8))
print('{} x{:2} = {:2}'.format(n, 1, n*9))
print('{} x{:2} = {:2}'.format(n, 1, n*10))
print('-'*12)
